### ISSUE TITLE
What does the robot you used look like? Can you help me build mine?

### ISSUE THREAD

**Issue by HEITORNERY** [larsll/deepracer-pi#12]
I want to build a robot with Raspberry Pi 4 and using ROS 2 Humble, but I didn't find information on your github about the robot you are using. I would like to know if you can help with information about assembling a robot that can use this repository. Images of the robot's circuit, of all the components it needs, of the connections with the robot, that would help a lot.

**Comment by davidfsmith** [comment]
Hello - I'm in the process of writing a blog post which details what's needed and how to connect it all up, should be live in the next few days or so - just need to finish it off and retake some photos

**Comment by HEITORNERY** [comment]
If possible, I would like the name of this blog and the link to the post. Thank you for your response and I look forward to your post.

**Comment by davidfsmith** [comment]
I'll update here once it's published.

**Comment by larsll** [comment]
So the parts are partially here: 
https://github.com/larsll/deepracer-pi/blob/main/BUILDING.md

It lacks the obvious though; it is a WLToys A979 you build it all on; and you will need a servo. Let's leave this ticket open to update the docs once the blog post is out.

**Comment by larsll** [comment]
Note: we have moved to https://github.com/aws-deepracer-community/deepracer-custom
