### ISSUE TITLE
Abount Hardware,such as camera

### ISSUE THREAD

**Issue by Trz-me** [larsll/deepracer-pi#6]
Greetings,

Your project has piqued my interest immensely, and I find the prospect of miniaturizing DeepRacer particularly intriguing. Could you please inform me if there are any specific requirements regarding the hardware composition and cable connections for this project?

For instance, is it imperative to use the official DeepLens camera?

The following image depicts a mini DeepRacer model vehicle I previously encountered, which base on  Raspberry Pi.
<img width="396" alt="image" src="https://github.com/larsll/deepracer-pi/assets/55552566/6140aa50-0991-4013-884b-1ade9cc39ce9">
<img width="501" alt="image" src="https://github.com/larsll/deepracer-pi/assets/55552566/168332c3-0d2f-48a5-a4a7-850b6510f79b">

**Comment by larsll** [comment]
I have added a Raspberry Pi Camera v2 on mine; it is almost better fitting (more resembling the picture in the simulator) than the one in the original car. The importance is the horizontal field-of-view (60 degrees); and the position (height over track, 15 degrees tilt forward and position ahead of the front tires). You might see some 3d print instructions to fit it onto the WLToys A949, A959, A979 later.

You don't really need any specific cables; but the Servo Hat from Waveshare would be needed. (It is the interface between RPi and the Servo/ESC.)

**Comment by larsll** [comment]
Closing as no further discussion.
